name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache/Restore dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: .
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Setup dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
          pipenv install --dev
    - name: Unit Tests
      working-directory: .
      run: |
        pipenv run pytest --cov
